### PR TITLE
Updates for 5.35 hotfix

### PR DESCRIPTION
**Pull request by reiichi001**
Grabbed by comparing diff from Sapphire server. Only tested that PennyPincher worked.

### CODE REVIEW

**Comment by karashiiro** [comment]
Those opcodes are all pre-hotfix, they don't work anymore.

**Comment by karashiiro** [comment]
Wait, only some of them are outdated, History and TaxRates.

**Comment by karashiiro** [comment]
MarketBoardHistory = 390,
MarketTaxRates = 504,

**Comment by karashiiro** [comment]
Oh, they're not outdated, they're just from the diff. Most of the diff is right but there's always a couple random ones it mismatches.

**Comment by reiichi001** [comment]
Updated the PR with those. Hopefully that means it's good to go now.

**Comment by goaaats** [comment]
Thanks guys, appreciate it

**Pull request merged**
